"""initial schema

Revision ID: ed83e70d8510
Revises: 
Create Date: 2026-04-02 23:41:19.143717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ed83e70d8510'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('knowledge_base',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_domain_id'), 'knowledge_base', ['domain_id'], unique=False)
    op.create_table('ticket_classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.String(length=50), nullable=False),
    sa.Column('predicted_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_department', sa.String(length=50), nullable=False),
    sa.Column('predicted_priority', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('domain_id', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_ticket_id', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submitter_name', sa.String(length=100), nullable=True),
    sa.Column('submitter_email', sa.String(length=150), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index('idx_tickets_custom', 'tickets', ['custom_fields'], unique=False, postgresql_using='gin')
    op.create_index('idx_tickets_domain_status', 'tickets', ['domain_id', 'status'], unique=False)
    op.create_index('idx_tickets_source', 'tickets', ['source_system', 'source_ticket_id'], unique=False)
    op.create_index(op.f('ix_tickets_domain_id'), 'tickets', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_domain_id'), table_name='tickets')
    op.drop_index('idx_tickets_source', table_name='tickets')
    op.drop_index('idx_tickets_domain_status', table_name='tickets')
    op.drop_index('idx_tickets_custom', table_name='tickets', postgresql_using='gin')
    op.drop_table('tickets')
    op.drop_table('ticket_embeddings')
    op.drop_table('ticket_classifications')
    op.drop_index(op.f('ix_knowledge_base_domain_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
